"use client";
import { useMemo, useState } from "react";
import { AlertTriangle, BarChart3, Check, Coins, Download, Gauge, Search, UsersRound, X } from "lucide-react";

type UserRow={id:string;email:string;name:string;status:string;balance:number;spent:number;apiCost:number;revenue:number;recharges:number;images:number;analyses:number;storageMb:number;profit:number;lastActivity:string;createdAt:string;onboarding:boolean;brands:string[];ledger:Array<{amount:number;reason:string;createdAt:string}>};
type Recharge={id:string;folio:string;user_id:string;package:string;amount_usd:number;credits:number;status:string;note:string|null;created_at:string;email:string;name:string;old:boolean};
export type AdminDashboardData={metrics:{spent:number;apiCost:number;revenue:number;profit:number;limit:number;storageGb:number;openaiCost:number;anthropicCost:number;images:number;analyses:number};users:UserRow[];recharges:Recharge[];pricing:Array<{module:string;credits:number;average:number;price:number;margin:number}>};

export function AdminConsole({data}:{data:AdminDashboardData}){const[query,setQuery]=useState("");const[filter,setFilter]=useState("all");const[selected,setSelected]=useState<UserRow|null>(null);const[busy,setBusy]=useState("");const users=useMemo(()=>data.users.filter(u=>(`${u.name} ${u.email}`).toLowerCase().includes(query.toLowerCase())).filter(u=>filter==="all"||filter==="active"&&u.status==="active"||filter==="empty"&&u.balance<50||filter==="inactive"&&u.status!=="active"||filter==="recharge"&&u.recharges>0).sort((a,b)=>filter==="top"?b.spent-a.spent:0),[data.users,query,filter]);
async function action(payload:Record<string,unknown>){setBusy(String(payload.requestId||payload.userId||"action"));const response=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();setBusy("");if(!response.ok)return alert(result.error);window.location.reload()}
function csv(){const head=["Correo","Nombre","Estado","Saldo","Gastados","Costo API","Profit","Recargas","Imágenes","Análisis","Storage MB","Última actividad"];const rows=users.map(u=>[u.email,u.name,u.status,u.balance,u.spent,u.apiCost.toFixed(3),u.profit.toFixed(2),u.recharges,u.images,u.analyses,u.storageMb.toFixed(1),u.lastActivity]);const blob=new Blob([[head,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="anapau-usuarios.csv";a.click();URL.revokeObjectURL(url)}
const limitPct=Math.min(100,data.metrics.apiCost/data.metrics.limit*100);return <section className="admin-shell admin-operations"><div className="panel-heading split"><div><span className="eyebrow">Panel madre · este mes</span><h1>Operación y rentabilidad.</h1><p>Créditos, costo real, recargas y actividad en una sola lectura.</p></div><div className={`admin-limit ${limitPct>=80?"danger":""}`}><span>Tope API</span><b>{limitPct.toFixed(0)}%</b><div><i style={{width:`${limitPct}%`}}/></div><small>${data.metrics.apiCost.toFixed(2)} de ${data.metrics.limit}</small></div></div><div className="admin-metrics admin-metrics-live"><article><Coins/><span>Créditos gastados</span><b>{data.metrics.spent.toLocaleString("es-MX")}</b><small>${(data.metrics.spent*.01).toFixed(2)} precio · ${data.metrics.apiCost.toFixed(2)} costo</small></article><article><BarChart3/><span>Ingresos</span><b>${data.metrics.revenue.toFixed(2)}</b><small>Recargas aprobadas</small></article><article><Gauge/><span>Profit</span><b>${data.metrics.profit.toFixed(2)}</b><small>Después de API y storage</small></article><article><UsersRound/><span>Producción</span><b>{data.metrics.images}</b><small>{data.metrics.analyses} análisis · {data.metrics.storageGb.toFixed(2)} GB</small></article></div><div className="provider-split"><span>OpenAI <b>${data.metrics.openaiCost.toFixed(2)}</b></span><span>Anthropic <b>${data.metrics.anthropicCost.toFixed(2)}</b></span></div>
{data.recharges.length>0&&<section className="admin-recharge-queue"><header><div><span className="eyebrow">Recargas pendientes</span><h2>Confirmaciones por resolver</h2></div><b>{data.recharges.length}</b></header>{data.recharges.map(r=><article key={r.id}><div><b>{r.folio} · {r.name}</b><small>{r.email} · {r.package} · {new Date(r.created_at).toLocaleDateString("es-MX")}</small></div><span>${r.amount_usd} · {r.credits.toLocaleString("es-MX")} cr</span><button disabled={busy===r.id} onClick={()=>action({action:"approve_recharge",requestId:r.id})}><Check/>Aprobar</button><button className="danger" disabled={busy===r.id} onClick={()=>{const reason=prompt("Motivo del rechazo");if(reason)action({action:"reject_recharge",requestId:r.id,reason})}}><X/>Rechazar</button></article>)}</section>}
<section className="admin-user-section"><header><div><span className="eyebrow">Usuarias</span><h2>Rentabilidad individual</h2></div><div className="admin-table-tools"><label><Search/><input placeholder="Buscar correo o nombre" value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas</option><option value="active">Activas</option><option value="empty">Sin saldo</option><option value="inactive">Inactivas</option><option value="top">Top consumo</option><option value="recharge">Con recargas</option></select><button onClick={csv}><Download/>CSV</button></div></header><div className="admin-table-wrap"><table><thead><tr><th>Usuaria</th><th>Estado</th><th>Saldo</th><th>Gastados</th><th>Costo API</th><th>Profit</th><th>Recargas</th><th>Imágenes</th><th>Análisis</th><th>Storage</th><th>Actividad</th></tr></thead><tbody>{users.map(u=><tr key={u.id} onClick={()=>setSelected(u)}><td><b>{u.name}</b><small>{u.email}</small></td><td><span className={`admin-badge ${u.status}`}>{u.status}</span></td><td>{u.balance.toLocaleString("es-MX")}</td><td>{u.spent.toLocaleString("es-MX")}</td><td>${u.apiCost.toFixed(3)}</td><td className={u.profit>=0?"profit":"loss"}>${u.profit.toFixed(2)}</td><td>${u.revenue.toFixed(0)} · {u.recharges}</td><td>{u.images}</td><td>{u.analyses}</td><td>{u.storageMb.toFixed(1)} MB</td><td>{new Date(u.lastActivity).toLocaleDateString("es-MX")}</td></tr>)}</tbody></table></div></section>
<section className="admin-pricing"><header><span className="eyebrow">Costos y precios</span><h2>Margen vivo por acción</h2></header><div className="admin-table-wrap"><table><thead><tr><th>Acción</th><th>Créditos</th><th>Precio equivalente</th><th>Costo API promedio</th><th>Margen</th></tr></thead><tbody>{data.pricing.map(p=><tr key={p.module}><td>{p.module}</td><td>{p.credits}</td><td>${p.price.toFixed(2)}</td><td>${p.average.toFixed(4)}</td><td>{p.margin?`${p.margin.toFixed(1)}x`:"Sin datos"}</td></tr>)}</tbody></table></div></section>
<section className="admin-alerts"><AlertTriangle/><div><b>Alertas operativas</b><p>{data.users.filter(u=>u.balance<50).length} usuarias con menos de 50 créditos · {data.users.filter(u=>!u.onboarding).length} onboarding incompletos · {data.recharges.filter(r=>r.old).length} recargas con más de 24 horas.</p></div></section>
{selected&&<div className="admin-drawer"><button onClick={()=>setSelected(null)}><X/></button><span className="eyebrow">Detalle de usuaria</span><h2>{selected.name}</h2><p>{selected.email}</p><div className="drawer-kpis"><span><b>{selected.balance}</b> saldo</span><span><b>${selected.apiCost.toFixed(3)}</b> costo API</span><span><b>${selected.profit.toFixed(2)}</b> profit</span></div><p><b>Marcas:</b> {selected.brands.join(", ")||"Sin marca"}</p><div className="drawer-actions"><button onClick={()=>{const amount=Number(prompt("Créditos a regalar"));const reason=prompt("Motivo");if(amount&&reason)action({action:"grant",userId:selected.id,amount,reason})}}>Regalar créditos</button><button onClick={()=>action({action:"status",userId:selected.id,status:selected.status==="active"?"inactive":"active"})}>{selected.status==="active"?"Desactivar":"Activar"}</button></div><h3>Últimos movimientos</h3>{selected.ledger.map((l,i)=><article key={i}><span>{l.reason}</span><b>{l.amount}</b><time>{new Date(l.createdAt).toLocaleDateString("es-MX")}</time></article>)}</div>}</section>}
