create table if not exists public.golden_briefs (
  id uuid primary key default gen_random_uuid(),
  archetype_id text not null references public.static_archetypes(id) on delete cascade,
  scope text not null default 'global' check (scope in ('global','brand')),
  brand_id uuid references public.brands(id) on delete cascade,
  ficha jsonb not null,
  source text not null default 'curated',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.brand_visual_identity (
  brand_id uuid primary key references public.brands(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  colores_hex text[] not null default '{}',
  tipografia_estilo text not null default 'sans_geometrica',
  luz_y_foto text,
  estilo_general text,
  source_asset_ids uuid[] not null default '{}',
  updated_at timestamptz not null default now()
);

alter table public.static_creatives add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.golden_briefs enable row level security;
alter table public.brand_visual_identity enable row level security;
drop policy if exists "golden_briefs_read" on public.golden_briefs;
create policy "golden_briefs_read" on public.golden_briefs for select using (scope = 'global' or auth.uid() = (select owner_id from public.brands where id = brand_id));
drop policy if exists "golden_briefs_insert_own" on public.golden_briefs;
create policy "golden_briefs_insert_own" on public.golden_briefs for insert with check (scope='brand' and auth.uid()=(select owner_id from public.brands where id=brand_id));
drop policy if exists "brand_visual_identity_owner" on public.brand_visual_identity;
create policy "brand_visual_identity_owner" on public.brand_visual_identity for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

insert into public.static_archetypes (id,name,label_visible,stage,structure,prompt_fragment,thumbnail_path,sort_order,active)
values
('beneficios_apilados','Beneficios claros','Beneficios claros','Consideración','{"estructura":{"zona_superior":"headline 2 líneas","zona_media":"3 píldoras + producto héroe táctil","zona_inferior":"1 badge CTA"},"art_direction_default":{"decision_visual_fuerte":"producto con gotas reales en macro","iluminacion":"softbox difuso con brillo especular","camara_y_encuadre":"producto 3/4 en tercio derecho","superficie_y_entorno":"gradiente suave de marca","props":"ninguno","tratamiento_color":"paleta + un acento"},"reglas":["máximo 4 beneficios de 4 palabras","producto 40-55%","un badge"]}','Headline + beneficios escaneables + producto héroe. Comprensión total en dos segundos.','/archetypes/beneficios_apilados.jpg',10,true),
('antes_despues_sutil','Antes y después','Antes y después','Retargeting','{"estructura":{"zona_superior":"perfil de marca discreto","zona_media":"dos fotos comparables","zona_inferior":"labels + oferta"},"art_direction_default":{"decision_visual_fuerte":"misma pose, luz y prenda; mejora sutil","iluminacion":"luz natural idéntica","camara_y_encuadre":"crop cerrado idéntico","superficie_y_entorno":"fondo neutro real","props":"ninguno","tratamiento_color":"natural sin retoque aparente"},"reglas":["mejora sutil Meta-safe","disclaimer de resultados"]}','Prueba visual honesta y comparable, nunca transformación dramática.','/archetypes/antes_despues_sutil.jpg',20,true),
('busqueda_solucion','La búsqueda','La búsqueda','Descubrimiento','{"estructura":{"zona_superior":"barra con pregunta real","zona_media":"producto como solución","zona_inferior":"escena lifestyle"},"art_direction_default":{"decision_visual_fuerte":"lineup ordenado en escena real","iluminacion":"sol directo con sombras reales","camara_y_encuadre":"frontal a nivel de producto","superficie_y_entorno":"alberca o repisa de baño","props":"máximo uno","tratamiento_color":"vivo y sin filtro"},"reglas":["query en lenguaje del avatar","UI creíble"]}','Formato nativo de búsqueda: pregunta exacta del avatar y producto como respuesta.','/archetypes/busqueda_solucion.jpg',30,true),
('resultados_busqueda','Resultados de búsqueda','Resultados de búsqueda','Descubrimiento','{"estructura":{"zona_superior":"barra y tabs","zona_media":"grid de resultados variados","zona_inferior":"continuación del grid"},"art_direction_default":{"decision_visual_fuerte":"selfies, producto y lifestyle como resultados genuinos","iluminacion":"mixta por celda","camara_y_encuadre":"grid regular","superficie_y_entorno":"UI clara","props":"ninguno","tratamiento_color":"variedad coherente"},"reglas":["mínimo seis celdas","query como hook"]}','Grid nativo que convierte la marca en la respuesta dominante.','/archetypes/resultados_busqueda.jpg',40,true),
('regalo_kit','Regalo con compra','Regalo con compra','Conversión','{"estructura":{"zona_superior":"regalo + condición","zona_media":"manos con productos y precios","zona_inferior":"CTA + fine print"},"art_direction_default":{"decision_visual_fuerte":"manos reales sosteniendo el regalo","iluminacion":"luz suave frontal","camara_y_encuadre":"manos entrando desde abajo","superficie_y_entorno":"gradiente bicolor suave","props":"un sticker","tratamiento_color":"pastel + acento"},"reglas":["precio tachado visible","máximo dos regalos"]}','Valor tangible con manos reales, regalo visible y condición clara.','/archetypes/regalo_kit.jpg',50,true),
('descuento_desbloqueado','Descuento desbloqueado','Descuento desbloqueado','Conversión','{"estructura":{"zona_superior":"porcentaje gigante","zona_media":"lineup en baño + badge","zona_inferior":"escena continúa"},"art_direction_default":{"decision_visual_fuerte":"bodegón sobre azulejo con textil táctil","iluminacion":"luz lateral de baño","camara_y_encuadre":"frontal elevada","superficie_y_entorno":"azulejo + toalla","props":"una toalla o flor","tratamiento_color":"neutros + acento"},"reglas":["porcentaje dominante","un badge sin código"]}','Gamificación: el descuento se siente como un logro personal.','/archetypes/descuento_desbloqueado.jpg',60,true),
('producto_heroe_editorial','Producto héroe','Producto héroe','Descubrimiento','{"estructura":{"zona_superior":"headline editorial","zona_media":"producto 50% + textura física","zona_inferior":"tres datos"},"art_direction_default":{"decision_visual_fuerte":"splash real congelado","iluminacion":"estudio brillante con reflejos limpios","camara_y_encuadre":"frontal heroico contrapicado","superficie_y_entorno":"gradiente saturado controlado","props":"máximo dos ingredientes","tratamiento_color":"vibrante sin HDR"},"reglas":["tres datos máximo","splash físico"]}','Producto gigante, textura táctil y datos concretos: clásico DTC elevado.','/archetypes/producto_heroe_editorial.jpg',70,true),
('collage_lifestyle','Collage aspiracional','Collage aspiracional','Descubrimiento','{"estructura":{"zona_superior":"celdas lifestyle","zona_media":"tarjeta central + producto sticker","zona_inferior":"más celdas"},"art_direction_default":{"decision_visual_fuerte":"carrete de amiga con marcos finos","iluminacion":"natural por celda","camara_y_encuadre":"grid 3x4","superficie_y_entorno":"fondo claro de marca","props":"producto con contorno blanco","tratamiento_color":"coherencia cálida"},"reglas":["seis a diez celdas","una tarjeta central"]}','Moodboard de la vida que desea el avatar con producto recortado.','/archetypes/collage_lifestyle.jpg',80,true),
('declaracion_contraria','Declaración con actitud','Declaración con actitud','Descubrimiento','{"estructura":{"zona_superior":"headline gigante","zona_media":"producto o modelo real","zona_inferior":"dos bullets o badges"},"art_direction_default":{"decision_visual_fuerte":"tipografía sobre foto real profunda","iluminacion":"flash editorial o sol duro","camara_y_encuadre":"vertical de cuerpo o mano","superficie_y_entorno":"contexto real simple","props":"ninguno","tratamiento_color":"dos colores de texto"},"reglas":["headline máximo ocho palabras","empoderamiento"]}','El copy es el visual: rompe una creencia con una frase memorable.','/archetypes/declaracion_contraria.jpg',90,true),
('post_its','Post-its de venta flash','Post-its de venta flash','Conversión','{"estructura":{"zona_superior":"primer post-it","zona_media":"oferta + producto","zona_inferior":"último post-it"},"art_direction_default":{"decision_visual_fuerte":"tocador y espejo reales con notas físicas","iluminacion":"ventana dorada lateral","camara_y_encuadre":"frontal al espejo","superficie_y_entorno":"tocador de madera","props":"florero máximo","tratamiento_color":"cálido + notas de marca"},"reglas":["máximo tres post-its","texto manuscrito layered"]}','Urgencia doméstica y personal en notas físicas, no bloques digitales.','/archetypes/post_its.jpg',100,true),
('ticket_novedad','Ticket de compra','Ticket de compra','Conversión','{"estructura":{"zona_superior":"ticket saliendo","zona_media":"oferta + ítems exactos","zona_inferior":"ahorro + código"},"art_direction_default":{"decision_visual_fuerte":"ticket físico perforado con sombra real","iluminacion":"sol exterior","camara_y_encuadre":"ticket centrado 60%","superficie_y_entorno":"lifestyle desenfocado","props":"ninguno","tratamiento_color":"papel blanco + mono"},"reglas":["números exactos layered","máximo tres ítems"]}','El ahorro convertido en un objeto físico y novedoso.','/archetypes/ticket_novedad.jpg',110,true),
('checklist_toggles','Nosotros vs ellos','Nosotros vs ellos','Consideración','{"estructura":{"zona_superior":"producto + headline","zona_media":"tarjeta con toggles","zona_inferior":"foto real continúa"},"art_direction_default":{"decision_visual_fuerte":"tarjeta oscura translúcida sobre piel real","iluminacion":"natural cálida","camara_y_encuadre":"tarjeta central + producto","superficie_y_entorno":"foto real de uso","props":"ninguno","tratamiento_color":"verde sistema + gris"},"reglas":["cuatro positivos y dos negativos","sin marcas competidoras"]}','Comparación objetiva en toggles, rápida y sin nombrar competidores.','/archetypes/checklist_toggles.jpg',120,true),
('chat_imessage','Chat de amigas','Chat de amigas','Retargeting','{"estructura":{"zona_superior":"nuevo mensaje","zona_media":"dos o tres burbujas","zona_inferior":"grid de fotos"},"art_direction_default":{"decision_visual_fuerte":"UI fiel sobre foto lifestyle","iluminacion":"exterior brillante","camara_y_encuadre":"chat 70% del ancho","superficie_y_entorno":"agua o arena real","props":"emojis discretos","tratamiento_color":"UI real + fondo vivo"},"reglas":["texto layered","tono de amiga real"]}','Recomendación natural disfrazada de conversación privada.','/archetypes/chat_imessage.jpg',130,true),
('anotaciones_manuscritas','Regalo señalado a mano','Regalo señalado a mano','Conversión','{"estructura":{"zona_superior":"anotación + flecha","zona_media":"persona con productos","zona_inferior":"condición + flecha"},"art_direction_default":{"decision_visual_fuerte":"foto casera creíble con tinta blanca","iluminacion":"luz natural de cuarto","camara_y_encuadre":"medio cuerpo frontal","superficie_y_entorno":"habitación real","props":"ninguno","tratamiento_color":"natural + tinta blanca"},"reglas":["dos notas y dos flechas","handwritten layered"]}','Foto UGC con anotaciones que señalan valor sin sentirse producida.','/archetypes/anotaciones_manuscritas.jpg',140,true),
('diagrama_callouts','Producto explicado','Producto explicado','Consideración','{"estructura":{"zona_superior":"pregunta editorial","zona_media":"producto + líneas finas","zona_inferior":"perfil humano"},"art_direction_default":{"decision_visual_fuerte":"retrato editorial y líneas técnicas","iluminacion":"estudio dramático controlado","camara_y_encuadre":"perfil + producto primer plano","superficie_y_entorno":"degradado profundo","props":"ninguno","tratamiento_color":"color profundo + blanco"},"reglas":["máximo cinco callouts","líneas de un pixel"]}','Autoridad editorial: explica el producto con precisión visual.','/archetypes/diagrama_callouts.jpg',150,true),
('prueba_social_flotante','Comentarios reales','Comentarios reales','Retargeting','{"estructura":{"zona_superior":"headline corto","zona_media":"producto + comentarios","zona_inferior":"escena continúa"},"art_direction_default":{"decision_visual_fuerte":"producto monumental en escena natural","iluminacion":"luz suave de invernadero","camara_y_encuadre":"frontal bajo","superficie_y_entorno":"flores o textura real","props":"un roundel","tratamiento_color":"profundo + marca"},"reglas":["tres comentarios","testimonio individual"]}','Comentarios creíbles flotan alrededor de un producto monumental.','/archetypes/prueba_social_flotante.jpg',160,true),
('comparacion_ancla','Comparación de precio','Comparación de precio','Consideración','{"estructura":{"zona_superior":"headline de contraste","zona_media":"dos polaroids con precio","zona_inferior":"contexto + CTA"},"art_direction_default":{"decision_visual_fuerte":"dos tarjetas físicas levemente rotadas","iluminacion":"plana editorial","camara_y_encuadre":"frontal simétrico","superficie_y_entorno":"color pleno de marca","props":"ninguno","tratamiento_color":"fondo + blanco"},"reglas":["precios reales","gasto cotidiano del avatar"]}','Reencuadra el precio contra un gasto cotidiano relevante.','/archetypes/comparacion_ancla.jpg',170,true)
on conflict (id) do update set name=excluded.name,label_visible=excluded.label_visible,stage=excluded.stage,structure=excluded.structure,prompt_fragment=excluded.prompt_fragment,thumbnail_path=excluded.thumbnail_path,sort_order=excluded.sort_order,active=true;

update public.static_archetypes set active=false where id not in ('beneficios_apilados','antes_despues_sutil','busqueda_solucion','resultados_busqueda','regalo_kit','descuento_desbloqueado','producto_heroe_editorial','collage_lifestyle','declaracion_contraria','post_its','ticket_novedad','checklist_toggles','chat_imessage','anotaciones_manuscritas','diagrama_callouts','prueba_social_flotante','comparacion_ancla');

insert into public.golden_briefs(archetype_id,scope,ficha,source)
select v.archetype_id,'global',v.ficha,'founder_catalog'
from (values
('beneficios_apilados','{"concepto":"Producto recién salido de la regadera: gotas reales y beneficios limpios","texto_principal":"PIEL PRIMERO","texto_secundario":"Aclara mientras cuida tu piel","cta":"Pruébala hoy","text_render_mode":"layered","art_direction":{"decision_visual_fuerte":"empaque con gotas macro flotando 15 grados","iluminacion":"softbox frontal + brillo superior derecho","camara_y_encuadre":"producto 3/4 al 45% del lienzo","superficie_y_entorno":"lavanda a crema","props":"ninguno","tratamiento_color":"acento sólo en CTA"}}'::jsonb),
('producto_heroe_editorial','{"concepto":"Splash físico congelado con ingredientes reales","texto_principal":"LA MEJOR VERSIÓN","texto_secundario":"Tres razones para creer","cta":"Nuevo","text_render_mode":"layered","art_direction":{"decision_visual_fuerte":"splash a alta velocidad golpea el empaque","iluminacion":"estudio brillante","camara_y_encuadre":"frontal heroico contrapicado","superficie_y_entorno":"gradiente coral a ámbar","props":"dos ingredientes","tratamiento_color":"saturación controlada"}}'::jsonb),
('checklist_toggles','{"concepto":"La comparación ya resuelta en toggles","texto_principal":"CUIDADO QUE SÍ FUNCIONA","texto_secundario":"Cuatro atributos on, dos off","cta":"","text_render_mode":"layered","art_direction":{"decision_visual_fuerte":"tarjeta al 85% sobre piel real","iluminacion":"natural lateral","camara_y_encuadre":"tarjeta central y producto arriba","superficie_y_entorno":"piel real diversa","props":"ninguno","tratamiento_color":"café oscuro + verde sistema"}}'::jsonb)
) as v(archetype_id,ficha)
where not exists (select 1 from public.golden_briefs g where g.archetype_id=v.archetype_id and g.scope='global' and g.source='founder_catalog');
